// Lucide Icons helper — replaces Font Awesome
// Usage: icon('map-marker-alt', 'w-5 h-5 text-amber-400')
// Brand icons: brandIcon('facebook', 'w-5 h-5')

import {
  Accessibility,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUp,
  Award,
  Ban,
  Bath,
  Bed,
  Bell,
  BellOff,
  Bike,
  Binoculars,
  Book,
  BookOpen,
  Bookmark,
  Brain,
  Cake,
  Calendar,
  CalendarDays,
  CalendarPlus,
  Camera,
  Car,
  CarFront,
  ChartBar,
  ChartLine,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  CircleStop,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  CloudUpload,
  Coffee,
  Coins,
  Columns2,
  Compass,
  Cookie,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  Crosshair,
  Crown,
  Database,
  Download,
  Droplets,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Flag,
  FlagTriangleRight,
  Flame,
  FlipHorizontal,
  Forward,
  Frown,
  Fuel,
  Funnel,
  Gamepad,
  Gem,
  Gift,
  GitFork,
  GitMerge,
  Globe,
  GraduationCap,
  Grid2x2,
  HandCoins,
  HandHeart,
  HandMetal,
  Handshake,
  Heart,
  History,
  Hotel,
  IdCard,
  Image,
  Inbox,
  Info,
  Languages,
  Laptop,
  Leaf,
  Lightbulb,
  Link,
  List,
  LoaderCircle,
  Locate,
  Lock,
  LockOpen,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  MapPinned,
  Medal,
  Megaphone,
  Meh,
  MessageCircle,
  MessageCircleMore,
  MessageSquare,
  MessagesSquare,
  Milestone,
  Minimize,
  Minus,
  Moon,
  Music,
  Navigation,
  Palette,
  PawPrint,
  Pencil,
  Percent,
  Phone,
  Pizza,
  Play,
  Plug,
  Plus,
  Pointer,
  RadioTower,
  RefreshCw,
  Reply,
  Rocket,
  RotateCw,
  Route,
  Save,
  Scale,
  ScanEye,
  Search,
  Send,
  Settings,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Shrink,
  Signpost,
  Skull,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sofa,
  Sprout,
  SquareParking,
  Star,
  StarHalf,
  Store,
  Sun,
  Tag,
  ThumbsUp,
  Ticket,
  Trash,
  TriangleAlert,
  Trophy,
  Undo,
  Upload,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  UserX,
  Users,
  Utensils,
  WandSparkles,
  Wifi,
  WifiOff,
  Wine,
  X,
} from 'lucide'

// ── FA → Lucide mapping ──────────────────────────────────────────────
const FA_MAP = {
  'ad': Megaphone,
  'angry': Frown,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'award': Award,
  'balance-scale': Scale,
  'ban': Ban,
  'bed': Bed,
  'bell': Bell,
  'bell-slash': BellOff,
  'bicycle': Bike,
  'birthday-cake': Cake,
  'book': Book,
  'book-atlas': BookOpen,
  'bookmark': Bookmark,
  'brain': Brain,
  'broadcast-tower': RadioTower,
  'bullseye': Crosshair,
  'calendar': Calendar,
  'calendar-alt': CalendarDays,
  'calendar-plus': CalendarPlus,
  'camera': Camera,
  'car': Car,
  'car-side': CarFront,
  'chart-bar': ChartBar,
  'chart-line': ChartLine,
  'check': Check,
  'check-circle': CircleCheck,
  'check-double': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'circle': Circle,
  'circle-notch': LoaderCircle,
  'clipboard-check': ClipboardCheck,
  'clipboard-list': ClipboardList,
  'clock': Clock,
  'clone': Copy,
  'cloud': Cloud,
  'cloud-upload-alt': CloudUpload,
  'code-fork': GitFork,
  'code-merge': GitMerge,
  'coffee': Coffee,
  'cog': Settings,
  'cogs': Settings,
  'coins': Coins,
  'columns': Columns2,
  'comment': MessageCircle,
  'comment-dots': MessageCircleMore,
  'comments': MessagesSquare,
  'compass': Compass,
  'compress': Shrink,
  'compress-alt': Minimize,
  'cookie-bite': Cookie,
  'copy': Copy,
  'couch': Sofa,
  'crosshairs': Crosshair,
  'crown': Crown,
  'database': Database,
  'download': Download,
  'edit': Pencil,
  'envelope': Mail,
  'exchange-alt': ArrowRightLeft,
  'exclamation-circle': CircleAlert,
  'exclamation-triangle': TriangleAlert,
  'expand': Expand,
  'external-link-alt': ExternalLink,
  'eye': Eye,
  'eye-slash': EyeOff,
  'file-alt': FileText,
  'filter': Funnel,
  'fire': Flame,
  'fist-raised': HandMetal,
  'flag': Flag,
  'flag-checkered': FlagTriangleRight,
  'flip-horizontal': FlipHorizontal,
  'forward': Forward,
  'frown': Frown,
  'gamepad': Gamepad,
  'gas-pump': Fuel,
  'gavel': Scale,
  'gem': Gem,
  'gift': Gift,
  'glass-martini-alt': Wine,
  'globe': Globe,
  'globe-americas': Globe,
  'graduation-cap': GraduationCap,
  'hand-holding-heart': HandHeart,
  'hand-holding-usd': HandCoins,
  'hand-pointer': Pointer,
  'handshake': Handshake,
  'heart': Heart,
  'history': History,
  'hotel': Hotel,
  'id-card': IdCard,
  'image': Image,
  'inbox': Inbox,
  'info-circle': Info,
  'language': Languages,
  'laptop': Laptop,
  'leaf': Leaf,
  'lightbulb': Lightbulb,
  'link': Link,
  'list': List,
  'location-arrow': Navigation,
  'location-crosshairs': Locate,
  'location-dot': MapPin,
  'lock': Lock,
  'magic': WandSparkles,
  'map': Map,
  'map-location-dot': MapPinned,
  'map-marked-alt': MapPinned,
  'map-marker-alt': MapPin,
  'map-pin': MapPin,
  'map-signs': Signpost,
  'medal': Medal,
  'meh': Meh,
  'minus': Minus,
  'mobile-alt': Smartphone,
  'moon': Moon,
  'mug-hot': Coffee,
  'mug-saucer': Coffee,
  'music': Music,
  'palette': Palette,
  'paper-plane': Send,
  'parking': SquareParking,
  'paw': PawPrint,
  'percent': Percent,
  'person': User,
  'phone': Phone,
  'phone-alt': Phone,
  'pizza-slice': Pizza,
  'play': Play,
  'plug': Plug,
  'plus': Plus,
  'plus-circle': CirclePlus,
  'question': Info,
  'question-circle': Info,
  'reply': Reply,
  'restroom': Bath,
  'road': Milestone,
  'rocket': Rocket,
  'rotate-right': RotateCw,
  'route': Route,
  'save': Save,
  'search': Search,
  'search-location': Search,
  'seedling': Sprout,
  'share': Share,
  'share-alt': Share2,
  'shield-alt': Shield,
  'shield-check': ShieldCheck,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  'shower': ShowerHead,
  'sign-in-alt': LogIn,
  'sign-out-alt': LogOut,
  'skull-crossbones': Skull,
  'sliders-h': SlidersHorizontal,
  'smile': Smile,
  'sms': MessageSquare,
  'spinner': LoaderCircle,
  'star': Star,
  'star-half-alt': StarHalf,
  'stop': CircleStop,
  'store': Store,
  'street-view': Binoculars,
  'sun': Sun,
  'sync-alt': RefreshCw,
  'tag': Tag,
  'th': Grid2x2,
  'thumbs-up': ThumbsUp,
  'ticket-alt': Ticket,
  'times': X,
  'times-circle': CircleX,
  'trash': Trash,
  'trash-alt': Trash,
  'trophy': Trophy,
  'tshirt': Shirt,
  'turn-left': CornerDownLeft,
  'turn-right': CornerDownRight,
  'undo': Undo,
  'universal-access': Accessibility,
  'unlock': LockOpen,
  'upload': Upload,
  'user': User,
  'user-check': UserCheck,
  'user-clock': UserCog,
  'user-friends': Users,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  'user-secret': ScanEye,
  'user-slash': UserX,
  'user-times': UserX,
  'users': Users,
  'users-cog': UserCog,
  'users-slash': Users,
  'utensils': Utensils,
  'wand-magic-sparkles': WandSparkles,
  'water': Droplets,
  'wifi': Wifi,
  'wifi-slash': WifiOff,
}

// ── Brand SVGs (inline, ~200-400 bytes each) ─────────────────────────
const BRANDS = {
  facebook: '<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/>',
  apple: '<path d="M12 2C9.5 2 8.4 3.6 8 4.5c-.4-.3-1.2-.7-2.2-.5C4 4.3 3 5.8 3 7.5c0 2.5 1.5 5.5 3 7.5 1 1.3 2 2.5 3 2.5.8 0 1.3-.4 2-.4s1.2.4 2 .4c1 0 2-1.2 3-2.5 1.5-2 3-5 3-7.5 0-1.7-1-3.2-2.8-3.5-1-.2-1.8.2-2.2.5-.4-.9-1.5-2.5-4-2.5z"/><path d="M12 2c0 1.5-.5 3-2 4"/>',
  google: '<path d="M21.8 10.4h-9.5v3.5h5.5c-.5 2.5-2.7 4.1-5.5 4.1-3.3 0-6-2.7-6-6s2.7-6 6-6c1.5 0 2.8.5 3.9 1.4l2.6-2.6C17.1 3.2 14.7 2 12 2 6.5 2 2 6.5 2 12s4.5 10 10 10c5 0 9.5-3.5 10-8.5.1-.7 0-1.4 0-2.1-.1-.3-.1-.7-.2-1z"/>',
  whatsapp: '<path d="M17.5 14.4c-.3-.15-1.7-.85-2-1-.3-.1-.5-.15-.7.15-.2.3-.75.95-.9 1.15-.2.2-.35.2-.65.05-1.8-.9-3-1.6-4.2-3.6-.3-.55.3-.5.9-1.7.1-.2.05-.35-.025-.5-.075-.15-.7-1.7-.95-2.3-.25-.6-.5-.55-.7-.55h-.6c-.2 0-.5.075-.8.375-.25.3-1 1-1 2.4s1.025 2.8 1.175 3c.15.2 2 3.1 4.9 4.35 1.8.8 2.5.85 3.4.7.55-.1 1.7-.7 1.95-1.35.25-.7.25-1.25.175-1.375-.075-.125-.275-.2-.575-.35zM12.05 21.8c-1.75 0-3.45-.45-4.95-1.35l-.35-.2-3.7 1 1-3.6-.25-.4A9.8 9.8 0 0 1 2.2 12c0-5.4 4.4-9.8 9.85-9.8 2.6 0 5.1 1 6.95 2.9a9.7 9.7 0 0 1 2.9 6.9c0 5.45-4.45 9.8-9.85 9.8zM20.5 3.5A11.8 11.8 0 0 0 12.05 0C5.5 0 .15 5.35.15 11.95c0 2.1.55 4.15 1.6 5.95L0 24l6.3-1.65c1.75.95 3.7 1.45 5.75 1.45C18.6 23.8 24 18.5 24 11.9c0-3.15-1.25-6.15-3.5-8.4z"/>',
  telegram: '<path d="M22 2L11 13"/><path d="M22 2L15 22l-4-9-9-4z"/>',
  twitter: '<path d="M4 4l7.1 8.5L4 20h1.7l6.2-6.5L17 20h5l-7.5-9L21 4h-1.7l-5.7 6L9 4z"/>',
  instagram: '<rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="5"/><circle cx="17.5" cy="6.5" r="1.5"/>',
  github: '<path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.4 5.4 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65S8.93 17.38 9 18v4"/><path d="M9 18c-4.51 2-5-2-7-2"/>',
  waze: '<circle cx="12" cy="12" r="10"/><circle cx="9" cy="10" r="1.5" fill="currentColor"/><circle cx="15" cy="10" r="1.5" fill="currentColor"/><path d="M8 15c1.3 1.3 2.7 2 4 2s2.7-.7 4-2"/>',
  paypal: '<path d="M7.1 19.5H4.3c-.4 0-.7-.3-.6-.7L6.5 3.3c.1-.3.3-.5.6-.5h5.5c1.8 0 3.2.5 4 1.4.7.8 1 1.9.7 3.2-.6 3-3 4.6-6 4.6H9.4c-.4 0-.7.3-.8.7l-.8 4.8c0 .3-.3.5-.6.5z"/><path d="M19.5 8.3c-.6 3-3 4.6-6 4.6h-1.9c-.4 0-.7.3-.8.7l-1 6.2c0 .3.2.5.5.5h2.8c.4 0 .6-.3.7-.6l.6-3.5c.1-.4.4-.7.8-.7h.5c2.7 0 4.8-1.5 5.3-4.1.3-1.3.1-2.3-.5-3.1z"/>',
}

// ── SVG string builder (no DOM needed) ───────────────────────────────
function buildSvg(iconNode, cls, size) {
  const children = iconNode.map(([tag, attrs]) => {
    const a = Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(' ')
    return `<${tag} ${a}/>`
  }).join('')

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide ${cls}" aria-hidden="true">${children}</svg>`
}

// ── Main helper ──────────────────────────────────────────────────────
export function icon(name, cls = '', size = 20) {
  const key = name.replace(/^fa-/, '')
  const iconNode = FA_MAP[key]
  if (!iconNode) {
    if (BRANDS[key]) return brandIcon(key, cls, size)
    return ''
  }
  return buildSvg(iconNode, cls, size)
}

// ── Brand icon helper ────────────────────────────────────────────────
export function brandIcon(name, cls = '', size = 20) {
  const paths = BRANDS[name]
  if (!paths) return ''
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="currentColor" stroke="none" class="lucide-brand ${cls}" aria-hidden="true">${paths}</svg>`
}

// ── Spinning icon (replaces fa-spinner fa-spin) ──────────────────────
export function spinnerIcon(cls = '', size = 20) {
  return icon('spinner', `animate-spin ${cls}`, size)
}
